# Generated by Django 2.2.5 on 2020-05-03 16:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'ordering': ('category_name',), 'verbose_name': 'Product Category', 'verbose_name_plural': 'Product Categories'},
        ),
    ]
