# Generated by Django 2.2.5 on 2020-05-03 16:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0002_auto_20200503_1822'),
    ]

    operations = [
        migrations.AddField(
            model_name='supplier',
            name='web_address',
            field=models.URLField(blank=True, verbose_name='Web Address'),
        ),
    ]
