# Generated by Django 2.2.5 on 2020-05-04 14:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0004_auto_20200504_1559'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='supplier_category',
            options={'ordering': ('category_id',), 'verbose_name': 'Categories By Supplier', 'verbose_name_plural': 'Product Categories By Suppliers'},
        ),
        migrations.AlterField(
            model_name='product',
            name='category_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to='product.Supplier_Category', verbose_name='Category'),
        ),
    ]
