# Generated by Django 2.2.5 on 2020-05-04 14:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0005_auto_20200504_1619'),
    ]

    operations = [
        migrations.AddField(
            model_name='supplier_category',
            name='description',
            field=models.CharField(default=0, max_length=50, verbose_name='Description'),
            preserve_default=False,
        ),
    ]
