# Generated by Django 2.2.5 on 2020-05-05 12:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0006_supplier_category_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='category_id',
            field=models.ForeignKey(limit_choices_to={'is_active': True}, on_delete=django.db.models.deletion.CASCADE, related_name='products', to='product.Supplier_Category', verbose_name='Category'),
        ),
        migrations.AlterField(
            model_name='supplier_category',
            name='description',
            field=models.CharField(help_text='Description that will be displayed in the category list of the Product', max_length=50, verbose_name='Description'),
        ),
    ]
