# Generated by Django 2.2.5 on 2020-05-05 13:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0007_auto_20200505_1454'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='warrenty_period',
            field=models.PositiveIntegerField(help_text='The warrenty period in years.', verbose_name='Warrenty Period'),
        ),
    ]
